version: 2.1
orbs:
  docker: circleci/docker@2.2.0
jobs:
  build-and-push:
    machine:
      image: ubuntu-2004:202101-01
      docker_layer_caching: false
    resource_class: arm.medium
    steps:
      - checkout
      - run: 
          name: Setup Custom Environment Variables & Add Version
          command: |
            echo "export REPO_NAME=$(printf '%s\n' \"${CIRCLE_PROJECT_REPONAME,,}\")" >> $BASH_ENV && \
            echo "export USER=$(printf '%s\n' \"${CIRCLE_PROJECT_USERNAME,,}\")" >> $BASH_ENV && \
            export VERSION=${CIRCLE_TAG:-NIGHTLY.$(date --rfc-3339=seconds | sed 's/[ :+]/-/g')} && \
            echo "export VERSION=$VERSION" >> $BASH_ENV && \
            echo $VERSION > version.txt
      - docker/check:
          docker-username: CIRCLE_PROJECT_USERNAME
          registry: ghcr.io
      - docker/build:
          image: $USER/$REPO_NAME
          tag: $VERSION
          registry: ghcr.io
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $USER/$REPO_NAME
          tag: $VERSION
          registry: ghcr.io
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  build:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: main
            tags: # see: https://circleci.com/blog/publishing-to-github-releases-via-circleci/
              only: /(?<=^[Vv]|^)(?:(?<major>(?:0|[1-9](?:(?:0|[1-9])+)*))[.](?<minor>(?:0|[1-9](?:(?:0|[1-9])+)*))[.](?<patch>(?:0|[1-9](?:(?:0|[1-9])+)*))(?:-(?<prerelease>(?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:0|[1-9](?:(?:0|[1-9])+)*))(?:[.](?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:0|[1-9](?:(?:0|[1-9])+)*)))*))?(?:[+](?<build>(?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:(?:0|[1-9])+))(?:[.](?:(?:(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?|(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)(?:[A-Za-z]|-)(?:(?:(?:0|[1-9])|(?:[A-Za-z]|-))+)?)|(?:(?:0|[1-9])+)))*))?)$/